# Generated by Django 3.2.25 on 2025-06-07 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250607_2019'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='receita',
            table='receita',
        ),
    ]
