# Generated by Django 3.2.25 on 2025-06-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_receita_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.IntegerField(help_text='Em minutos', verbose_name='Tempo de Preparo'),
        ),
    ]
